# -*- coding: utf-8 -*-
"""mpmc_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197hzbwxS9goth_v1PERx0U8d_V4mJuTx
"""

!unzip mpmc_training.zip

import pandas as pd
import numpy as np
import glob
from scipy.signal import welch
import os

# --- 1. Helper Function for FFT ---

def calculate_band_power(data, fs, freq_band):
    """
    Calculates the total power in a specific frequency band.
    """
    # Use Welch's method for a cleaner power spectrum (PSD)
    freqs, psd = welch(data, fs=fs, nperseg=len(data))

    # Find the indices of the frequencies that fall within our band
    band_indices = np.where((freqs >= freq_band[0]) & (freqs <= freq_band[1]))[0]

    if len(band_indices) == 0:
        return 0 # No power in this band

    # Sum up all the power values (PSD) within the band
    total_power = np.sum(psd[band_indices])

    return total_power

# --- 2. Feature Extraction Function ---

def process_files(file_list, output_filename):
    """
    Loads raw CSV files, extracts features from the "rest" data (first 30s),
    and saves them to a new CSV.
    """

    # --- Parameters ---
    WINDOW_SECONDS = 5.0
    FREQUENCY_HZ = 50
    SAMPLES_PER_WINDOW = int(WINDOW_SECONDS * FREQUENCY_HZ) # 250 samples
    OVERLAP_PERCENTAGE = 50
    STEP_SIZE = 10

    # Frequency band for tremor
    TREMOR_BAND = [4, 6] # 4 Hz to 6 Hz

    # --- IMPORTANT: We only process the "rest" data ---
    # 30 seconds * 50 Hz = 1500 rows
    SAMPLES_TO_PROCESS = 1500

    all_feature_vectors = []

    print(f"\n--- Processing {output_filename} ---")
    print(f"Found {len(file_list)} files.")

    for file in file_list:
        try:
            # Load the raw data
            df = pd.read_csv(file)

            # --- THIS IS THE KEY: We filter for "rest" data ---
            # We select ONLY the first 1500 rows (30 seconds)
            raw_data = df[['ax', 'ay', 'az', 'gx', 'gy', 'gz']].values[:SAMPLES_TO_PROCESS]

            # Slide a window over this 1500-row chunk of "rest" data
            for i in range(0, len(raw_data) - SAMPLES_PER_WINDOW, STEP_SIZE):
                window = raw_data[i : i + SAMPLES_PER_WINDOW]

                # --- Calculate Features for this Window ---
                std_devs = np.std(window, axis=0)
                means = np.mean(window, axis=0)

                powers_4_6hz = []
                for col_index in range(window.shape[1]): # Iterate 0 through 5
                    axis_data = window[:, col_index]
                    power = calculate_band_power(axis_data, FREQUENCY_HZ, TREMOR_BAND)
                    powers_4_6hz.append(power)

                # Combine all 18 features into one vector
                feature_vector = np.concatenate((std_devs, means, np.array(powers_4_6hz)))
                all_feature_vectors.append(feature_vector)

        except Exception as e:
            print(f"Error processing {file}: {e}")

    print(f"Feature extraction complete. Total windows created: {len(all_feature_vectors)}")

    # --- Save the Final Dataset ---
    feature_columns = [
        'ax_std', 'ay_std', 'az_std', 'gx_std', 'gy_std', 'gz_std',
        'ax_mean', 'ay_mean', 'az_mean', 'gx_mean', 'gy_mean', 'gz_mean',
        'ax_4_6hz_pwr', 'ay_4_6hz_pwr', 'az_4_6hz_pwr',
        'gx_4_6hz_pwr', 'gy_4_6hz_pwr', 'gz_4_6hz_pwr'
    ]

    features_df = pd.DataFrame(all_feature_vectors, columns=feature_columns)
    features_df.to_csv(output_filename, index=False)
    print(f"Successfully saved final features to '{output_filename}'")

# --- 3. Main Execution ---

# ⚠️ IMPORTANT: Change this to the name of your unzipped folder!
# It's probably the name of the .zip file you uploaded.
DATA_FOLDER = 'mpmc_training'

# Define your 10 training files based on your screenshot
train_filenames = [
    'healthy_final_data_01.csv',
    'healthy_final_data_03.csv',
    'healthy_final_data_04.csv',
    'healthy_final_data_05.csv',
    'healthy_final_data_06.csv',
    'healthy_final_data_08.csv',
    'healthy_final_data_09.csv',
    'healthy_final_data_10.csv',
    'healthy_final_data_11.csv',
    'healthy_final_data_12.csv'
]

# Define your 2 test files
test_filenames = [
    'healthy_final_data_13.csv',
    'healthy_final_data_14.csv'
]

# Create the full file paths
# os.path.join correctly adds the '/'
train_files = [os.path.join(DATA_FOLDER, f) for f in train_filenames]
test_files = [os.path.join(DATA_FOLDER, f) for f in test_filenames]

# --- Run the processing for both sets ---
process_files(train_files, 'train_features.csv')
process_files(test_files, 'test_features.csv')

print("\nAll processing complete. You now have 'train_features.csv' and 'test_features.csv'.")

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
import joblib

# --- 1. Load Your Feature Datasets ---

try:
    train_df = pd.read_csv('train_features.csv')
    test_df = pd.read_csv('test_features.csv')
    print(f"Loaded training data with {train_df.shape[0]} windows.")
    print(f"Loaded test data with {test_df.shape[0]} windows.")
except FileNotFoundError:
    print("Error: 'train_features.csv' or 'test_features.csv' not found.")
    print("Please make sure you've run the feature extraction cell first.")

# --- 2. Pre-process the Data (CRITICAL STEP) ---

# Autoencoders are very sensitive to the scale of data.
# We will scale all features to have a mean of 0 and std dev of 1.

# IMPORTANT: We fit the scaler ONLY on the training data
scaler = StandardScaler()
train_data_scaled = scaler.fit_transform(train_df)

# We use the SAME scaler (with the mean/std from train) to transform the test data
test_data_scaled = scaler.transform(test_df)

print("\nData successfully scaled.")

# --- 3. Build the Autoencoder Model ---

n_features = train_data_scaled.shape[1] # Should be 18
encoding_dim = 8  # The "bottleneck" size. This is a good starting point.

model = keras.Sequential([
    # --- Encoder ---
    # Input layer (18 features)
    layers.Input(shape=(n_features,)),
    # First hidden layer
    layers.Dense(14, activation='relu'),
    # Bottleneck (8 features)
    layers.Dense(encoding_dim, activation='relu'),

    # --- Decoder ---
    # First decoding layer
    layers.Dense(14, activation='relu'),
    # Output layer (must match input shape: 18 features)
    layers.Dense(n_features, activation='linear') # Linear activation for reconstruction
])

# --- 4. Compile the Model ---
# We use 'mae' (Mean Absolute Error) as our loss function
model.compile(optimizer='adam', loss='mae')

model.summary()

# --- 5. Train the Model ---
print("\n--- Starting Model Training ---")

# We train the model to reconstruct its own input
# x = train_data, y = train_data
history = model.fit(
    train_data_scaled,
    train_data_scaled,
    epochs=100,
    batch_size=16,
    shuffle=True,
    validation_data=(test_data_scaled, test_data_scaled) # Use test data for validation
)

print("--- Model Training Complete ---")

# --- 6. Find the Anomaly Threshold ---
print("\n--- Finding Anomaly Threshold ---")

# Get the model's predictions (reconstructions) for the TEST data
reconstructions = model.predict(test_data_scaled)

# Calculate the Mean Absolute Error for EACH window in the test set
# This is our "reconstruction error" score
test_loss_mae = mean_absolute_error(test_data_scaled.T, reconstructions.T, multioutput='raw_values')

# Find the highest error from our "healthy" test set
max_error = np.max(test_loss_mae)

# Set our final threshold to be just above the max error
# (e.g., 10% buffer)
FINAL_THRESHOLD = max_error * 1.1

print(f"Max reconstruction error on healthy test data: {max_error:.4f}")
print(f"FINAL ANOMALY THRESHOLD (with 10% buffer): {FINAL_THRESHOLD:.4f}")

# --- 7. Save the Model and Scaler ---
# We need to save BOTH the model and the scaler

# Save the trained model
model.save('autoencoder_model.h5')
print("\nSuccessfully saved trained model to 'autoencoder_model.h5'")

# Save the scaler
joblib.dump(scaler, 'scaler.joblib')
print("Successfully saved data scaler to 'scaler.joblib'")

print("\n--- All Done! ---")

